-- =====================================================
-- Asynchronous Ingestion Pipeline - Database Setup
-- =====================================================
-- This migration creates the necessary tables and functions
-- for the async content ingestion system.
--
-- Run this script in your Supabase SQL Editor.
-- =====================================================

-- =====================================================
-- 1. Create ingestion_jobs table
-- =====================================================
-- This table acts as a job queue for content ingestion tasks.
-- Workers poll this table to find pending jobs.

CREATE TABLE IF NOT EXISTS public.ingestion_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

  -- Job status: 'pending', 'processing', 'completed', 'failed'
  status TEXT NOT NULL DEFAULT 'pending',

  -- The content payload from the external system
  -- Stores: unique_content_id, course_slug, course_name, topic_id,
  --         model, version, title, module, notes, version_data, content
  payload JSONB NOT NULL,

  -- Error message if the job failed
  error_message TEXT NULL,

  -- Optional: track processing time
  processed_at TIMESTAMP WITH TIME ZONE NULL,

  -- Constraints
  CONSTRAINT valid_status CHECK (status IN ('pending', 'processing', 'completed', 'failed'))
);

-- =====================================================
-- 2. Create indexes for performance
-- =====================================================

-- Index for worker queries: Find oldest pending jobs quickly
-- Partial index only on pending jobs for efficiency
CREATE INDEX IF NOT EXISTS idx_ingestion_jobs_pending
  ON public.ingestion_jobs (created_at)
  WHERE (status = 'pending');

-- Index for monitoring: Find jobs by status
CREATE INDEX IF NOT EXISTS idx_ingestion_jobs_status
  ON public.ingestion_jobs (status, created_at DESC);

-- Index for looking up jobs by unique_content_id (for debugging)
CREATE INDEX IF NOT EXISTS idx_ingestion_jobs_content_id
  ON public.ingestion_jobs ((payload->>'unique_content_id'));

-- =====================================================
-- 3. Create trigger to update updated_at timestamp
-- =====================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_ingestion_jobs_updated_at ON public.ingestion_jobs;

CREATE TRIGGER update_ingestion_jobs_updated_at
  BEFORE UPDATE ON public.ingestion_jobs
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 4. Create atomic dequeue function for workers
-- =====================================================
-- This function atomically fetches the next pending job and marks it as processing.
-- Using FOR UPDATE SKIP LOCKED ensures multiple workers don't grab the same job.

CREATE OR REPLACE FUNCTION public.dequeue_ingestion_job()
RETURNS SETOF public.ingestion_jobs
LANGUAGE plpgsql
AS $$
DECLARE
  job_row public.ingestion_jobs;
BEGIN
  -- Find the oldest 'pending' job, lock it, update it to 'processing', and return it
  UPDATE public.ingestion_jobs
  SET
    status = 'processing',
    processed_at = NOW()
  WHERE id = (
    SELECT id
    FROM public.ingestion_jobs
    WHERE status = 'pending'
    ORDER BY created_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED  -- This prevents race conditions between workers
  )
  RETURNING * INTO job_row;

  -- Return the job row (or NULL if no jobs available)
  IF job_row.id IS NOT NULL THEN
    RETURN NEXT job_row;
  END IF;

  RETURN;
END;
$$;

-- =====================================================
-- 5. Optional: Create helper function to reset stuck jobs
-- =====================================================
-- This function can be used to reset jobs that have been "processing" for too long
-- (e.g., if a worker crashed). Run this manually or via a cron job.

CREATE OR REPLACE FUNCTION public.reset_stuck_jobs(
  stuck_threshold_minutes INTEGER DEFAULT 30
)
RETURNS TABLE (
  reset_count INTEGER
)
LANGUAGE plpgsql
AS $$
DECLARE
  affected_rows INTEGER;
BEGIN
  UPDATE public.ingestion_jobs
  SET
    status = 'pending',
    error_message = CONCAT('Job was stuck in processing state. Reset at ', NOW()),
    updated_at = NOW()
  WHERE
    status = 'processing'
    AND updated_at < (NOW() - (stuck_threshold_minutes || ' minutes')::INTERVAL);

  GET DIAGNOSTICS affected_rows = ROW_COUNT;

  reset_count := affected_rows;
  RETURN NEXT;
END;
$$;

-- =====================================================
-- 6. Grant necessary permissions
-- =====================================================
-- Ensure the service role can access these objects
-- (Adjust if using a different role)

GRANT ALL ON public.ingestion_jobs TO service_role;
GRANT ALL ON public.ingestion_jobs TO postgres;

-- =====================================================
-- 7. Optional: Create view for monitoring
-- =====================================================

CREATE OR REPLACE VIEW public.ingestion_jobs_stats AS
SELECT
  status,
  COUNT(*) as count,
  MIN(created_at) as oldest,
  MAX(created_at) as newest,
  AVG(EXTRACT(EPOCH FROM (COALESCE(processed_at, NOW()) - created_at))) as avg_wait_seconds
FROM public.ingestion_jobs
GROUP BY status;

-- =====================================================
-- Setup complete!
-- =====================================================
--
-- Verification queries:
--
-- Check table exists:
--   SELECT * FROM public.ingestion_jobs LIMIT 1;
--
-- Check stats:
--   SELECT * FROM public.ingestion_jobs_stats;
--
-- Manually reset stuck jobs (if needed):
--   SELECT reset_stuck_jobs(30); -- Reset jobs stuck for 30+ minutes
--
-- =====================================================
